---
apiVersion: v1
kind: Secret
metadata:
  name: repominder-web
data:
  DJ_SUPERUSER: "${DJ_SUPERUSER_B64}"
  DJ_SUPERUSER_EMAIL: "${DJ_SUPERUSER_EMAIL_B64}"
  DJ_SUPERUSER_PASSWORD: "${DJ_SUPERUSER_PASSWORD_B64}"
  GHAPP_CLIENT_SECRET: "${GHAPP_CLIENT_SECRET_B64}"
  GHAPP_PRIVKEY: "${GHAPP_PRIVKEY_B64}"
  GHAPP_WEBHOOK_SECRET: "${GHAPP_WEBHOOK_SECRET_B64}"
  RAVEN_DSN: "${RAVEN_DSN_B64}"
  SECRET_KEY: "${SECRET_KEY_B64}"
  SES_ID: "${SES_ID_B64}"
  SES_KEY: "${SES_KEY_B64}"
---
apiVersion: v1
kind: Secret
metadata:
  name: repominder-cert
data:
  tls.crt: "${CF_ORIGIN_CERT_B64}"
  tls.key: "${CF_ORIGIN_KEY_B64}"
