---

- name: create venv directory
  file: path={{ venv }} state=directory owner={{ appuser }} group={{ appgroup }}
  sudo: yes

- name: install venv exec
  template: src=venv_exec.j2 dest={{ venv }}/exec mode=755

- cron: name="run djsupervisor on startup"
        special_time="reboot"
        user="{{ appuser }}"
        job="cd {{ appdir }}; {{ venv }}/exec python manage.py supervisor --daemonize"
        cron_file="djsupervisor_startup"
  sudo: yes
