# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 18:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseWatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_branch', models.TextField(blank=True, default='')),
                ('release_branch', models.TextField(blank=True, default='')),
                ('tag_pattern', models.TextField(blank=True, default='')),
                ('style', models.CharField(choices=[('DB', 'dual branch'), ('TP', 'tag pattern')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Repo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='repo',
            name='users',
            field=models.ManyToManyField(through='core.UserRepo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='releasewatch',
            name='userrepo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.UserRepo'),
        ),
        migrations.AlterUniqueTogether(
            name='userrepo',
            unique_together=set([('repo', 'user')]),
        ),
        migrations.AlterField(
            model_name='releasewatch',
            name='dev_branch',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='releasewatch',
            name='dev_branch',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='releasewatch',
            name='release_branch',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='releasewatch',
            name='tag_pattern',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='repo',
            name='full_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='releasewatch',
            name='dev_branch',
            field=models.CharField(help_text='The branch that tracks the latest code (ie, where pull requests are merged to).', max_length=256),
        ),
        migrations.AlterField(
            model_name='releasewatch',
            name='release_branch',
            field=models.CharField(blank=True, default='', help_text='The branch that tracks the latest released code.', max_length=256),
        ),
        migrations.AlterField(
            model_name='releasewatch',
            name='tag_pattern',
            field=models.CharField(blank=True, default='^\\d+\\.\\d+\\.\\d+$', help_text='A python regex to match release tags. The default matches 3-part semver.', max_length=256),
        ),
        migrations.AlterField(
            model_name='releasewatch',
            name='release_branch',
            field=models.CharField(blank=True, default='', help_text='The branch that tracks the most recent release.', max_length=256),
        ),
        migrations.AlterField(
            model_name='releasewatch',
            name='dev_branch',
            field=models.CharField(help_text='The branch that tracks the latest code (ie, where pull requests are merged to).', max_length=256, verbose_name='development branch'),
        ),
        migrations.AlterField(
            model_name='releasewatch',
            name='tag_pattern',
            field=models.CharField(blank=True, default='*.*.*', help_text='A shell pattern to match release tags. The default matches 3-part semver. <a href="https://docs.python.org/2/library/fnmatch.html">More details</a>.', max_length=256),
        ),
    ]
