# Generated by Django 2.2.16 on 2020-11-22 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20201122_0219"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="releasewatch",
            name="userrepo",
        ),
        migrations.AddField(
            model_name="releasewatch",
            name="repo",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.Repo",
            ),
            preserve_default=False,
        ),
    ]
