# Generated by Django 2.2.16 on 2020-11-29 17:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_auto_20201129_1743"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="last_userrepo_refresh",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
