# Generated by Django 2.2.16 on 2020-11-29 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0008_auto_20201129_1746"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInstall",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.Installation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("installation", "user")},
            },
        ),
        migrations.AddField(
            model_name="installation",
            name="users",
            field=models.ManyToManyField(
                through="core.UserInstall", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
