---

- name: Add duplicity ppa
  apt_repository: repo='{{ backup_duplicity_ppa }}' update_cache=yes
  when: backup_duplicity_ppa

- name: Install dependencies
  apt: pkg={{item}}
  with_items:
    - cron
    - gzip
    - python-boto
    - s3cmd

- set_fact: backup_duplicity_pkg="{{backup_duplicity_pkg}}={{backup_duplicity_version}}"
  when: backup_duplicity_version

- name: Install duplicity
  apt: pkg={{backup_duplicity_pkg}}

- name: Install pydrive
  pip: name=pydrive
  sudo: yes
