---

- hosts: appservers
  remote_user: "{{ appuser }}"
  vars_files:
      - secrets.yml
  vars:
      - pydrive_key: "{{ lookup('file', '../secrets/pydriveprivatekey.pem') }}"
  roles:
    - role: common
    - ANXS.python
    - role: Stouts.backup
      sudo: true
      tags: backup
      backup_profiles:
        - name: repominder_db4
          schedule: "0 23 * * *"
          source: "{{ approot }}"
          exclude:
             - "{{ assetdir }}"
             - "{{ appdir }}"
             - "{{ deploydir }}"
             - "{{ venv }}"
          target: "pydrive://{{ pydrive_user }}/repominder_backups/db4"
          action: 'backup_verify_purge --force'
    - runapp
