---

- hosts: all
  remote_user: "{{ appuser }}"
  vars_files:
      - secrets.yml
  # We can't gather facts ahead of time since it'll fail unless the port is changed.
  # The sshport role will gather them after ensuring the port is changed.
  gather_facts: false
  roles:
    - role: dmsimard.sshport
    - role: common
    - role: Yannik.enable-standard-cronjobs
      sudo: true
    - role: jnv.unattended-upgrades
      sudo: true
    - role: ricbra.logentries
      sudo: true
      tags: logentries
    - role: Oefenweb.fail2ban
      sudo: true
    - role: sivel.newrelic
      sudo: true
    - role: geerlingguy.firewall
      sudo: true
