---

- hosts: deploytargets
  remote_user: "{{ appuser }}"
  tasks:
    - name: create stash to archive working copy
      local_action: command git stash create
      run_once: true
      register: stash

    - name: expand ref
      local_action: command git rev-parse --verify {{ stash.stdout | default("HEAD", true) }}
      run_once: true
      register: revparse

    - name: create git archive
      local_action: command git archive {{ revparse.stdout }} -o ops/{{ revparse.stdout }}.tar
      run_once: true

    - name: create deploy dir
      file: path={{ deploydir }} state=directory owner={{ appuser }} group={{ appgroup }}
      sudo: yes

    - name: push deploy tar
      copy: src={{revparse.stdout}}.tar dest={{ deploydir }}/{{revparse.stdout}}.tar owner={{ appuser }} group={{ appgroup }}

    - name: remove old code
      command: find {{ appdir }} -mindepth 1 -delete

    - name: unpack new code
      unarchive: copy=no src={{ deploydir }}/{{ revparse.stdout }}.tar dest={{ appdir }} owner={{ appuser }} group={{ appgroup }}

    - name: move in assets
      shell: "rm -rf {{ assetdir }}/*; mv {{ appdir }}/assets {{ assetdir }}"

    - name: add release file
      shell: "echo {{ revparse.stdout }} > {{ appdir }}/release.sha"

- include: post_deploy.yml
