---

- hosts: webservers
  remote_user: "{{ appuser }}"
  vars_files:
      - secrets.yml
  roles:
    - role: ssl
    - role: jdauphant.nginx
      sudo: yes
      nginx_sites:
        repominder:
          - server_name www.repominder.com
          - listen 443 ssl
          - ssl_certificate_key /etc/nginx/ssl/ssl.key
          - ssl_certificate /etc/nginx/ssl/ssl-unified.crt
          - client_max_body_size 1M
          - keepalive_timeout 5
          - root {{ assetdir }}
          # From https://gunicorn-docs.readthedocs.org/en/develop/deploy.html
          - location / {
              try_files $uri @proxy_to_app; 
            }
          - location @proxy_to_app {
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header Host $http_host;
              proxy_redirect off;
              proxy_pass  http://gunicorn;
            }
          # Turn off caching for everything.
          - expires off
        catchall:
          - listen 443 ssl default_server
          - ssl_certificate_key /etc/nginx/ssl/ssl.key
          - ssl_certificate /etc/nginx/ssl/ssl-unified.crt
          - return 444
      nginx_configs:
        upstream:
            - upstream gunicorn { server 127.0.0.1:8000 fail_timeout=0; }
